export enum AppRoles {
  aggregates_manage = "aggregates_manage",
  aggregates_view = "aggregates_view",
  datawarehouses_admin = "datawarehouses_admin",
  designcenter_user = "designcenter_user",
  query_user = "query_user",
  queries_manage = "queries_manage",
  queries_view = "queries_view",
  query_dataset_api_view = "query_dataset_api_view",
  superuser_user = "superuser_user",
  support_logs_view = "support_logs_view",
  repository_project_publish = "repository_project_publish",
  repository_project_read = "repository_project_read",
  application_admin = "application_admin",
  admin = "admin",
}
