name: "PR :: Workflow"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "PR :: Tests"
    steps:
      - name: "Git :: Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup :: Node"
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "NPM :: Install"          
        run: npm install

      - name: "NPM :: Lint"      
        run: npm run lint

      - name: "NPM :: Test"           
        run: npm run test

      - name: "NPM :: Build"   
        run: npm run build

      - name: "NPM :: Pack"   
        run: npm pack

      - name: "Store :: NPM Package"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sml-converters
          path: sml-converters-*.tgz
          retention-days: 14

      - name: "NPM :: Get sml-converters version"
        id: package_version
        run: echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: "NPM :: Install sml-converters globally"
        run: npm install -g sml-converters-${{ env.PACKAGE_VERSION }}.tgz
